// AUTO-GENERATED by scripts/extract_ansprechpartner.py
// Source: scrape-out/consolidated/pages (moosburg.de Verwaltungsgliederung
// + Telefonliste + 'Was finde ich wo'-Aufgabenkatalog).
// Do not edit by hand; re-run the script to refresh.

export type Ansprechpartner = {
  id: string;
  name: string;
  role: string;
  phone: string;
  email: string;
  zimmer: string;
  sachgebiet: string;
  leitung: string[];
  aufgaben: string[];
};

export type Sachgebiet = {
  id: string;
  name: string;
  leitung: string;
  stellvertretung: string;
  weitere: string[];
};

export const ansprechpartner: Ansprechpartner[] = [
  {
    id: "adamski-madeleine",
    name: "Adamski Madeleine",
    role: "",
    phone: "08761 684-18",
    email: "ewo@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.01",
    sachgebiet: "SG 12 Einwohnermelde- und Passamt",
    leitung: [],
    aufgaben: [
      "Antragsstatus Reisepass und Personalausweis",
      "Auskunftssperren",
      "Führungszeugnis",
      "Kinderreisepass",
      "Meldeauskünfte",
      "Personalausweis / vorläufiger Personalausweis",
      "Reisepass / vorläufiger Reisepass",
      "Wohnungswechsel - Abmeldung bei der Meldebehörde",
      "Wohnungswechsel - Anmeldung bei der Meldebehörde"
    ],
  },
  {
    id: "brandlmeier-susanne",
    name: "Brandlmeier Susanne",
    role: "",
    phone: "08761 684-25",
    email: "susanne.brandlmeier@moosburg.de",
    zimmer: "Sudetenlandstr. 14",
    sachgebiet: "",
    leitung: [],
    aufgaben: [
      "KFZ-Zulassungswesen"
    ],
  },
  {
    id: "braun-renate",
    name: "Braun Renate",
    role: "",
    phone: "08761 684-21",
    email: "renate.braun@moosburg.de",
    zimmer: "Huber-Haus, 1. OG, Zimmer H1.1",
    sachgebiet: "SG 13 Personal, Stadtbücherei, Archiv",
    leitung: [],
    aufgaben: [
      "Stellenangebote"
    ],
  },
  {
    id: "burghard-christoph",
    name: "Burghard Christoph",
    role: "",
    phone: "08761 684-819",
    email: "christoph.burghard@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 11",
    sachgebiet: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: [],
    aufgaben: [
      "Informations- und Kommunikationstechnik"
    ],
  },
  {
    id: "dr-stanglmaier-michael",
    name: "Dr. Stanglmaier Michael",
    role: "",
    phone: "08761 684-12 (Vorzimmer)",
    email: "info@moosburg.de",
    zimmer: "",
    sachgebiet: "Dritter Bürgermeister",
    leitung: [],
    aufgaben: [],
  },
  {
    id: "ebner-michaela",
    name: "Ebner Michaela",
    role: "",
    phone: "08761 684-52",
    email: "michaela.ebner@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer G1.1",
    sachgebiet: "SG Kommunaler Hochbau",
    leitung: [],
    aufgaben: [
      "Hallenbelegung",
      "Kommunaler Hochbau"
    ],
  },
  {
    id: "ecke-lea",
    name: "Ecke Lea",
    role: "",
    phone: "08761 684-38",
    email: "lea.ecke@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 12",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Abfallwirtschaft in Gemeinden",
      "Gewerbesteuer",
      "Grundsteuer A+B",
      "Hundesteuer",
      "Kämmerei"
    ],
  },
  {
    id: "eichner-laura",
    name: "Eichner Laura",
    role: "",
    phone: "08761 684-824",
    email: "laura.eichner@moosburg.de",
    zimmer: "Hypo-Gebäude, 3. Stock",
    sachgebiet: "SG 32 Bildungs- und Erziehungswesen, Stadtjugendpflege, KVÜ, Parkraumbewirtschaftung",
    leitung: [],
    aufgaben: [
      "Kindergartenbeiträge"
    ],
  },
  {
    id: "eitner-fabian",
    name: "Eitner Fabian",
    role: "",
    phone: "08761 684-827",
    email: "fabian.eitner@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 15",
    sachgebiet: "SG 11 Gewerbe-, Ordnungs-, Sozial-und Fundamt",
    leitung: [],
    aufgaben: [
      "Feuerwehrwesen",
      "Katastrophenschutz"
    ],
  },
  {
    id: "falkenstein-melanie",
    name: "Falkenstein Melanie",
    role: "",
    phone: "08761 684-54",
    email: "Melanie.Falkenstein@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer G1.1",
    sachgebiet: "SG Kommunaler Hochbau",
    leitung: [],
    aufgaben: [
      "Klimaschutzmanagerin"
    ],
  },
  {
    id: "federolf-claudia",
    name: "Federolf Claudia",
    role: "",
    phone: "08761 684-24",
    email: "claudia.federolf@moosburg.de",
    zimmer: "Hypo-Gebäude, 3. Stock",
    sachgebiet: "SG 32 Bildungs- und Erziehungswesen, Stadtjugendpflege, KVÜ, Parkraumbewirtschaftung",
    leitung: [],
    aufgaben: [
      "Ferienmaßnahmen",
      "Jugendzentrum",
      "Kindergartenbeiträge",
      "Parkgebühren, Verordnung über",
      "Verkehrsüberwachungsdienst"
    ],
  },
  {
    id: "fischer-johann",
    name: "Fischer Johann",
    role: "",
    phone: "08761 684-20",
    email: "johann.fischer@moosburg.de",
    zimmer: "Huber-Haus, 1. OG, Zimmer H1.2",
    sachgebiet: "SG 13 Personal, Stadtbücherei, Archiv",
    leitung: [
      "SG 13 Personal, Stadtbücherei, Archiv"
    ],
    aufgaben: [
      "Heimatpflege",
      "Personalangelegenheiten",
      "Stadtarchiv",
      "Stellenangebote"
    ],
  },
  {
    id: "gawron-karin",
    name: "Gawron Karin",
    role: "",
    phone: "08761 684-814",
    email: "karin.gawron@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 22",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Liegenschaftsverwaltung (Gemeinde)",
      "Miet- und Pachteinnahmen"
    ],
  },
  {
    id: "glueck-christina",
    name: "Glück Christina",
    role: "",
    phone: "08761 684-73",
    email: "christina.glueck@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 22 Beitrags- und Gebührenstelle",
    leitung: [
      "SG 22 Beitrags- und Gebührenstelle"
    ],
    aufgaben: [
      "Abwassergebühren",
      "Erschließungsbeiträge",
      "Herstellungbeiträge",
      "Straßenausbaubeiträge",
      "Wassergebühren"
    ],
  },
  {
    id: "grassl-thomas",
    name: "Graßl Thomas",
    role: "",
    phone: "08761 684-40",
    email: "thomas.grassl@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 20 Stadtbau- und Planungsamt, Tiefbau, Kaufm. Leitung Wasserwerk",
    leitung: [],
    aufgaben: [
      "Bauleitplanung",
      "Bauordnungsrecht",
      "Erschließungsbeiträge",
      "Herstellungbeiträge",
      "Städtebauförderung",
      "Städtebauliche- und Erschließungsverträge",
      "Straßenausbaubeiträge",
      "Umwelt-, Natur- und Landschaftsschutz",
      "Wassergebühren"
    ],
  },
  {
    id: "grassl-schier-beate",
    name: "Graßl-Schier Beate",
    role: "",
    phone: "08761 684-46",
    email: "beate.grassl-schier@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 21 Straßenverkehrsbehörde",
    leitung: [],
    aufgaben: [
      "Straßenverkehr, Ausnahmegenehmigungen für Veranstaltungen (örtliche Straßenverkehrsbehörde)",
      "Straßenverkehrsordnung; Ausnahmegenehmigungen",
      "Straßenverkehrsordnung; Baustellen",
      "Straßenverkehrsrecht"
    ],
  },
  {
    id: "grindl-janine",
    name: "Grindl Janine",
    role: "",
    phone: "08761 684-23",
    email: "janine.grindl@moosburg.de",
    zimmer: "Sudetenlandstr. 14",
    sachgebiet: "SG 14 Kraftfahrzeugzulassungsbehörde",
    leitung: [],
    aufgaben: [
      "KFZ-Zulassungswesen"
    ],
  },
  {
    id: "guyens-michael",
    name: "Guyens Michael",
    role: "",
    phone: "08761 9332",
    email: "Michael.Guyens@moosburg.de",
    zimmer: "",
    sachgebiet: "Stadtgärtnerei",
    leitung: [],
    aufgaben: [
      "Stadtgärtnerei"
    ],
  },
  {
    id: "goetz-maximilian",
    name: "Götz Maximilian",
    role: "",
    phone: "08761 684-13",
    email: "maximilian.goetz@moosburg.de",
    zimmer: "Huber-Haus, 3. OG, Zimmer H3.1",
    sachgebiet: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: [],
    aufgaben: [
      "Bürgerbegehren und Bürgerentscheide",
      "Bürgermeister- und Gemeinderatsangelegenheiten",
      "Bürgerversammlungen",
      "Kommunalrecht, allgemeine Angelegenheiten",
      "Ortsrecht",
      "Schüleraustausch",
      "Sitzungsniederschriften",
      "Sitzungsvorbereitung"
    ],
  },
  {
    id: "hadersdorfer-carmen",
    name: "Hadersdorfer Carmen",
    role: "",
    phone: "08761 684-35",
    email: "carmen.hadersdorfer@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 22",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Liegenschaftsverwaltung (Gemeinde)",
      "Miet- und Pachteinnahmen"
    ],
  },
  {
    id: "heigl-andreas",
    name: "Heigl Andreas",
    role: "",
    phone: "08761 684-47",
    email: "andreas.heigl@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 20 Stadtbau- und Planungsamt, Tiefbau, Kaufm. Leitung Wasserwerk",
    leitung: [],
    aufgaben: [
      "Breitbandversorgung",
      "Brückenbauwerke",
      "Straßenbau",
      "Straßenreinigung",
      "Straßenunterhalt"
    ],
  },
  {
    id: "held-herbert",
    name: "Held Herbert",
    role: "",
    phone: "08761 684-41",
    email: "herbert.held@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "Abteilung II Stadtbauamt",
    leitung: [
      "Abteilung II Stadtbauamt",
      "SG 20 Stadtbau- und Planungsamt, Tiefbau, Kaufm. Leitung Wasserwerk"
    ],
    aufgaben: [
      "Bauberatung",
      "Bauleitplanung",
      "Baurecht - Erlass örtlicher Bauvorschriften",
      "Denkmalpflege",
      "Stadtentwicklung",
      "Stadtplanung"
    ],
  },
  {
    id: "holzner-ingrid",
    name: "Holzner Ingrid",
    role: "",
    phone: "08761 684-65",
    email: "standesamt@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.03",
    sachgebiet: "SG 12 Standesamt",
    leitung: [],
    aufgaben: [
      "Anmeldung der Eheschließung",
      "Anzeige einer Geburt",
      "Ausstellung von Personenstandsurkunden",
      "Ehename",
      "Eheschließung im In- und Ausland",
      "Geburtsbeurkundung",
      "Kirchenaustritte",
      "Leichenpass",
      "Sterbebeurkundung",
      "Todesbescheinigungen"
    ],
  },
  {
    id: "holzner-martin",
    name: "Holzner Martin",
    role: "",
    phone: "08761 9332",
    email: "Martin.Holzner@moosburg.de",
    zimmer: "",
    sachgebiet: "Bauhof",
    leitung: [],
    aufgaben: [
      "Bauhof"
    ],
  },
  {
    id: "huether-julia",
    name: "Hüther Julia",
    role: "",
    phone: "08761 684-810",
    email: "julia.huether@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 21",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Abfallwirtschaft in Gemeinden",
      "Gewerbesteuer",
      "Grundsteuer A+B",
      "Hundesteuer",
      "Kämmerei"
    ],
  },
  {
    id: "johal-mangat-viktoria",
    name: "Johal-Mangat Viktoria",
    role: "",
    phone: "08761 684-818",
    email: "viktoria.johal-mangat@moosburg.de",
    zimmer: "Feyberabendhaus, 2. Stock, Zimmer 21",
    sachgebiet: "SG 31 Stadtkasse",
    leitung: [
      "SG 31 Stadtkasse"
    ],
    aufgaben: [
      "Stadtkasse"
    ],
  },
  {
    id: "jaeckel-tim",
    name: "Jäckel Tim",
    role: "",
    phone: "08761 684-92",
    email: "tim.jaeckel@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 11",
    sachgebiet: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: [],
    aufgaben: [
      "Informations- und Kommunikationstechnik"
    ],
  },
  {
    id: "juettner-karin",
    name: "Jüttner Karin",
    role: "",
    phone: "08761 684-16",
    email: "ewo@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.01",
    sachgebiet: "SG 12 Einwohnermelde- und Passamt",
    leitung: [
      "SG 12 Einwohnermelde- und Passamt",
      "SG 12 Standesamt"
    ],
    aufgaben: [
      "Anmeldung der Eheschließung",
      "Antragsstatus Reisepass und Personalausweis",
      "Anzeige einer Geburt",
      "Auskunftssperren",
      "Ausstellung von Personenstandsurkunden",
      "Auszug aus dem Gewerbezentralregister",
      "Beglaubigungen",
      "Ehename",
      "Eheschließung im In- und Ausland",
      "Führungszeugnis",
      "Geburtsbeurkundung",
      "Kinderreisepass",
      "Kirchenaustritte",
      "Leichenpass",
      "Meldeauskünfte",
      "Personalausweis / vorläufiger Personalausweis",
      "Reisepass / vorläufiger Reisepass",
      "Sterbebeurkundung",
      "Todesbescheinigungen",
      "Wohngeldantrag",
      "Wohnsitz - Hauptwohnung und Nebenwohnung",
      "Wohnungswechsel - Abmeldung bei der Meldebehörde",
      "Wohnungswechsel - Anmeldung bei der Meldebehörde"
    ],
  },
  {
    id: "kaminski-tobias",
    name: "Kaminski Tobias",
    role: "",
    phone: "08761 684-28",
    email: "tobias.kaminski@moosburg.de",
    zimmer: "Huber-Haus, 1. OG, Zimmer H1.2",
    sachgebiet: "SG 13 Personal, Stadtbücherei, Archiv",
    leitung: [],
    aufgaben: [
      "Personalangelegenheiten"
    ],
  },
  {
    id: "kaulich-claudia",
    name: "Kaulich Claudia",
    role: "",
    phone: "08761 684-62",
    email: "claudia.kaulich@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 15",
    sachgebiet: "SG 11 Gewerbe-, Ordnungs-, Sozial-und Fundamt",
    leitung: [],
    aufgaben: [
      "Bestattungsrecht",
      "Bestattungswesen; Überführungserlaubnis",
      "Feuerwerk, Abbrennerlaubnis",
      "Gaststättenrechtliche Gestattung",
      "Gewerbeanzeige",
      "Marktordnung",
      "Schutz von Sonn- und Feiertagen"
    ],
  },
  {
    id: "kern-angelika",
    name: "Kern Angelika",
    role: "",
    phone: "08761 684-17",
    email: "ewo@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.01",
    sachgebiet: "SG 12 Einwohnermelde- und Passamt",
    leitung: [],
    aufgaben: [
      "Antragsstatus Reisepass und Personalausweis",
      "Auskunftssperren",
      "Führungszeugnis",
      "Kinderreisepass",
      "Meldeauskünfte",
      "Personalausweis / vorläufiger Personalausweis",
      "Reisepass / vorläufiger Reisepass",
      "Wohnungswechsel - Abmeldung bei der Meldebehörde",
      "Wohnungswechsel - Anmeldung bei der Meldebehörde"
    ],
  },
  {
    id: "kirschner-martina",
    name: "Kirschner Martina",
    role: "",
    phone: "08761 684-828",
    email: "martina.kirschner@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 24",
    sachgebiet: "SG 31 Stadtkasse",
    leitung: [],
    aufgaben: [],
  },
  {
    id: "kollein-florian",
    name: "Kollein Florian",
    role: "",
    phone: "08761 684-823",
    email: "florian.kollein@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 21 Straßenverkehrsbehörde",
    leitung: [],
    aufgaben: [
      "Straßenverkehr, Ausnahmegenehmigungen für Veranstaltungen (örtliche Straßenverkehrsbehörde)",
      "Straßenverkehrsordnung; Ausnahmegenehmigungen",
      "Straßenverkehrsordnung; Baustellen",
      "Straßenverkehrsrecht"
    ],
  },
  {
    id: "kopp-stephan",
    name: "Kopp Stephan",
    role: "",
    phone: "08761 684-71",
    email: "stephan.kopp@moosburg.de",
    zimmer: "Feyerabendhaus, 1. OG, Zimmer 14",
    sachgebiet: "SG 13 Personal, Stadtbücherei, Archiv",
    leitung: [],
    aufgaben: [
      "Digitalisierung",
      "Stadtarchiv"
    ],
  },
  {
    id: "kreitmeier-stephanie",
    name: "Kreitmeier Stephanie",
    role: "",
    phone: "08761 684-66",
    email: "stephanie.kreitmeier@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 13",
    sachgebiet: "SG 11 Gewerbe-, Ordnungs-, Sozial-und Fundamt",
    leitung: [],
    aufgaben: [
      "Aufstellen von Spielgeräten mit Gewinnmöglichkeit - Erlaubnis",
      "Betretungs- und Befahrverbot von Grundstücken",
      "Feuerwerk, Abbrennerlaubnis",
      "Fischereischein",
      "Gaststättenrechtliche Gestattung",
      "Gewerbeanzeige",
      "Jagdscheinantrag",
      "Ladenschluss",
      "Marktgebühren",
      "Marktordnung",
      "Obdachlosigkeit, Vermeidung",
      "Ordnungswidrigkeiten; Bearbeitung",
      "Plakate, Öffentliche Anschläge",
      "Rentenanträge; Aufnahme",
      "Rundfunk- und Fernsehgebührenpflicht; Befreiung",
      "Schutz von Sonn- und Feiertagen",
      "Soziale Hilfsstelle",
      "Sperrzeit, Gaststätten",
      "Unterstützung hilfsbedürftiger Wohnungssuchender",
      "Vergnügungen, öffentliche - Anzeige/Erlaubnis",
      "Verordnung über Hunde mit gesteigerter Aggressivität und Gefährlichkeit",
      "Verordnung über Hundehaltung in Bayern - Maulkorbzwang und Anleinpflicht",
      "Wehr- und Zivildienst",
      "Wehrerfassung"
    ],
  },
  {
    id: "krumbucher-martin",
    name: "Krumbucher Martin",
    role: "",
    phone: "08761 684-30",
    email: "martin.krumbucher@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 26",
    sachgebiet: "Abteilung III Finanzwesen, Versicherungen, Steueramt, Liegenschaftsamt, Stadtkasse",
    leitung: [
      "Abteilung III Finanzwesen, Versicherungen, Steueramt, Liegenschaftsamt, Stadtkasse",
      "SG 30 Kämmerei, Steueramt, Liegenschaftsamt"
    ],
    aufgaben: [
      "Haushaltsplan der Gemeinde",
      "Konzessionsabgabe",
      "örtliche Rechnungsprüfung",
      "Zahlungsverkehr (Mahnung und Vollstreckung)",
      "Zuweisungen nach dem Finanzausgleichsgesetz"
    ],
  },
  {
    id: "koerger-tanja",
    name: "Körger Tanja",
    role: "",
    phone: "08761 684-821",
    email: "tanja.koerger@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 12",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Abfallwirtschaft in Gemeinden",
      "Gewerbesteuer",
      "Hundesteuer",
      "Kämmerei"
    ],
  },
  {
    id: "lauterbach-reinhard",
    name: "Lauterbach Reinhard",
    role: "",
    phone: "08761 684-12 (Vorzimmer)",
    email: "info@moosburg.de",
    zimmer: "",
    sachgebiet: "Zweiter Bürgermeister",
    leitung: [],
    aufgaben: [],
  },
  {
    id: "leicht-gabriele",
    name: "Leicht Gabriele",
    role: "",
    phone: "08761 684-95",
    email: "gabriele.leicht@moosburg.de",
    zimmer: "Sudetenlandstr. 14",
    sachgebiet: "SG 14 Kraftfahrzeugzulassungsbehörde",
    leitung: [],
    aufgaben: [
      "KFZ-Zulassungswesen"
    ],
  },
  {
    id: "linhart-franz",
    name: "Linhart Franz",
    role: "",
    phone: "08761 684-812",
    email: "franz.linhart@moosburg.de",
    zimmer: "Hypo-Gebäude, 3. Stock",
    sachgebiet: "SG 32 Bildungs- und Erziehungswesen, Stadtjugendpflege, KVÜ, Parkraumbewirtschaftung",
    leitung: [],
    aufgaben: [
      "Ferienmaßnahmen",
      "Gastschulverhältnisse",
      "Jugendzentrum",
      "Kindergartenbeiträge",
      "Parkgebühren, Verordnung über",
      "Verkehrsüberwachungsdienst"
    ],
  },
  {
    id: "linhart-jacqueline",
    name: "Linhart Jacqueline",
    role: "",
    phone: "08761 684-53",
    email: "jacqueline.linhart@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer G1.1",
    sachgebiet: "SG Kommunaler Hochbau",
    leitung: [],
    aufgaben: [
      "Kommunaler Hochbau"
    ],
  },
  {
    id: "littmann-heidemarie",
    name: "Littmann Heidemarie",
    role: "",
    phone: "08761 684-64",
    email: "heidi.littmann@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 13",
    sachgebiet: "SG 11 Gewerbe-, Ordnungs-, Sozial-und Fundamt",
    leitung: [],
    aufgaben: [
      "Aufstellen von Spielgeräten mit Gewinnmöglichkeit - Erlaubnis",
      "Fischereischein",
      "Fundsachen",
      "Gaststättenrechtliche Gestattung",
      "Gewerbeanzeige",
      "Plakate, Öffentliche Anschläge",
      "Rundfunk- und Fernsehgebührenpflicht; Befreiung",
      "Sondernutzung an Gemeindestraßen",
      "Soziale Hilfsstelle",
      "Vergnügungen, öffentliche - Anzeige/Erlaubnis"
    ],
  },
  {
    id: "ludwig-anja",
    name: "Ludwig Anja",
    role: "",
    phone: "08761 684-32",
    email: "anja.ludwig@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 24",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Anlagenbuchhaltung",
      "Kämmerei",
      "Vereinsförderung",
      "Vermögenserfassung"
    ],
  },
  {
    id: "mader-maximilian",
    name: "Mader Maximilian",
    role: "1. Bürgermeister",
    phone: "08761 684-11 (Vorzimmer)",
    email: "info@moosburg.de",
    zimmer: "Huber-Haus, 2. OG, Zimmer H2.1",
    sachgebiet: "Leitung der Stadtverwaltung",
    leitung: [
      "Leitung der Stadtverwaltung",
      "Erster Bürgermeister"
    ],
    aufgaben: [
      "Bürgermeister- und Gemeinderatsangelegenheiten"
    ],
  },
  {
    id: "maier-christine",
    name: "Maier Christine",
    role: "",
    phone: "08761 684-65",
    email: "standesamt@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.03",
    sachgebiet: "SG 12 Standesamt",
    leitung: [],
    aufgaben: [
      "Anmeldung der Eheschließung",
      "Anzeige einer Geburt",
      "Ausstellung von Personenstandsurkunden",
      "Ehename",
      "Eheschließung im In- und Ausland",
      "Geburtsbeurkundung",
      "Kirchenaustritte",
      "Leichenpass",
      "Sterbebeurkundung",
      "Todesbescheinigungen"
    ],
  },
  {
    id: "malyssek-mueller-karin",
    name: "Malyssek-Müller Karin",
    role: "",
    phone: "08761 684-37",
    email: "Karin.Malyssek-Mueller@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 21",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Anlagenbuchhaltung",
      "Vermögenserfassung",
      "Versicherungswesen"
    ],
  },
  {
    id: "mermer-petra",
    name: "Mermer Petra",
    role: "",
    phone: "08761 684-12",
    email: "petra.mermer@moosburg.de",
    zimmer: "Huber-Haus, 2. OG, Zimmer H2.1",
    sachgebiet: "Vorzimmer",
    leitung: [],
    aufgaben: [
      "Vorzimmer Bürgermeister/in"
    ],
  },
  {
    id: "morgenstern-aicke",
    name: "Morgenstern Aicke",
    role: "",
    phone: "08761 684-22",
    email: "aicke.morgenstern@moosburg.de",
    zimmer: "Hypo-Gebäude, 3. Stock",
    sachgebiet: "SG 32 Bildungs- und Erziehungswesen, Stadtjugendpflege, KVÜ, Parkraumbewirtschaftung",
    leitung: [
      "SG 32 Bildungs- und Erziehungswesen, Stadtjugendpflege, KVÜ, Parkraumbewirtschaftung"
    ],
    aufgaben: [
      "Ferienmaßnahmen",
      "Gastschulverhältnisse",
      "Jugendzentrum",
      "Kindergarten; Benutzungsordnung",
      "Kindergartenbeiträge",
      "Kostenfreiheit des Schulwegs",
      "Mittagsbetreuung an kommunalen Schulen",
      "Parkgebühren, Verordnung über",
      "Schulaufwandsträger",
      "Schulbuslinien",
      "Verkehrsüberwachungsdienst"
    ],
  },
  {
    id: "pfanzelt-nicole",
    name: "Pfanzelt Nicole",
    role: "",
    phone: "08761 684-815",
    email: "nicole.pfanzelt@moosburg.de",
    zimmer: "Huber-Haus, 2. OG, Zimmer H2.1",
    sachgebiet: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: [],
    aufgaben: [
      "Presse- und Öffentlichkeitsarbeit"
    ],
  },
  {
    id: "przybilla-diana",
    name: "Przybilla Diana",
    role: "",
    phone: "08761 684-33",
    email: "diana.przybilla@moosburg.de",
    zimmer: "Feyberabendhaus, 2. Stock, Zimmer 21",
    sachgebiet: "SG 31 Stadtkasse",
    leitung: [],
    aufgaben: [
      "Stadtkasse"
    ],
  },
  {
    id: "reif-bettina",
    name: "Reif Bettina",
    role: "",
    phone: "08761 684-39",
    email: "bettina.reif@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 24",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Kämmerei"
    ],
  },
  {
    id: "riedmaier-nicola",
    name: "Riedmaier Nicola",
    role: "",
    phone: "08761 684-27",
    email: "nicola.riedmaier@moosburg.de",
    zimmer: "Huber-Haus, 1. OG, Zimmer H1.1",
    sachgebiet: "SG 13 Personal, Stadtbücherei, Archiv",
    leitung: [],
    aufgaben: [
      "Personalangelegenheiten"
    ],
  },
  {
    id: "schafhauser-michael",
    name: "Schafhauser Michael",
    role: "",
    phone: "08761 684-74",
    email: "michael.schafhauser@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 22 Beitrags- und Gebührenstelle",
    leitung: [],
    aufgaben: [
      "Abwassergebühren",
      "Fäkalienabfuhr",
      "Kleineinleiterabgabe",
      "Wassergebühren"
    ],
  },
  {
    id: "scheckenhofer-marion",
    name: "Scheckenhofer Marion",
    role: "",
    phone: "08761 684-75",
    email: "marion.scheckenhofer@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 22 Beitrags- und Gebührenstelle",
    leitung: [],
    aufgaben: [
      "Abwassergebühren",
      "Erschließungsbeiträge",
      "Herstellungbeiträge",
      "Straßenausbaubeiträge",
      "Wassergebühren"
    ],
  },
  {
    id: "scherbakow-anna",
    name: "Scherbakow Anna",
    role: "",
    phone: "08761 684-34",
    email: "anna.scherbakow@moosburg.de",
    zimmer: "Feyberabendhaus, 2. Stock, Zimmer 21",
    sachgebiet: "SG 31 Stadtkasse",
    leitung: [],
    aufgaben: [
      "Stadtkasse"
    ],
  },
  {
    id: "schmid-birgit",
    name: "Schmid Birgit",
    role: "",
    phone: "08761 684-25",
    email: "Birgit.Schmid@moosburg.de",
    zimmer: "Sudetenlandstraße 14",
    sachgebiet: "SG 14 Kraftfahrzeugzulassungsbehörde",
    leitung: [],
    aufgaben: [
      "KFZ-Zulassungswesen"
    ],
  },
  {
    id: "schmid-manuela",
    name: "Schmid Manuela",
    role: "",
    phone: "08761 684-11",
    email: "manuela.schmid@moosburg.de",
    zimmer: "Huber-Haus, 2. OG, Zimmer H2.1",
    sachgebiet: "Vorzimmer",
    leitung: [],
    aufgaben: [
      "Vereinswesen",
      "Vorzimmer Bürgermeister/in"
    ],
  },
  {
    id: "schmid-verena",
    name: "Schmid Verena",
    role: "",
    phone: "08761 684-17",
    email: "ewo@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.01",
    sachgebiet: "SG 12 Einwohnermelde- und Passamt",
    leitung: [],
    aufgaben: [
      "Antragsstatus Reisepass und Personalausweis",
      "Auskunftssperren",
      "Führungszeugnis",
      "Kinderreisepass",
      "Meldeauskünfte",
      "Personalausweis / vorläufiger Personalausweis",
      "Reisepass / vorläufiger Reisepass",
      "Wohnungswechsel - Abmeldung bei der Meldebehörde",
      "Wohnungswechsel - Anmeldung bei der Meldebehörde"
    ],
  },
  {
    id: "schmidt-andreas",
    name: "Schmidt Andreas",
    role: "",
    phone: "08761 684-57",
    email: "Andreas.Schmidt@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer G1.1",
    sachgebiet: "SG Kommunaler Hochbau",
    leitung: [],
    aufgaben: [
      "Kommunaler Hochbau"
    ],
  },
  {
    id: "schroeder-claudia",
    name: "Schröder Claudia",
    role: "",
    phone: "08761 684-51",
    email: "claudia.schroeder@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer G1.1",
    sachgebiet: "SG Kommunaler Hochbau",
    leitung: [],
    aufgaben: [
      "Kommunaler Hochbau"
    ],
  },
  {
    id: "schwaiger-christine",
    name: "Schwaiger Christine",
    role: "",
    phone: "08761 684-17",
    email: "ewo@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.01",
    sachgebiet: "SG 12 Einwohnermelde- und Passamt",
    leitung: [],
    aufgaben: [
      "Antragsstatus Reisepass und Personalausweis",
      "Auskunftssperren",
      "Führungszeugnis",
      "Kinderreisepass",
      "Meldeauskünfte",
      "Personalausweis / vorläufiger Personalausweis",
      "Reisepass / vorläufiger Reisepass",
      "Wohnungswechsel - Abmeldung bei der Meldebehörde",
      "Wohnungswechsel - Anmeldung bei der Meldebehörde"
    ],
  },
  {
    id: "schwarzkugler-lisa",
    name: "Schwarzkugler Lisa",
    role: "",
    phone: "08761 684-94",
    email: "lisa.schwarzkugler@moosburg.de",
    zimmer: "Sudetenlandstr. 14",
    sachgebiet: "SG 14 Kraftfahrzeugzulassungsbehörde",
    leitung: [
      "SG 14 Kraftfahrzeugzulassungsbehörde"
    ],
    aufgaben: [
      "KFZ-Zulassungswesen"
    ],
  },
  {
    id: "setzensack-ingrid",
    name: "Setzensack Ingrid",
    role: "",
    phone: "08761 684-31",
    email: "ingrid.setzensack@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 25",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Kämmerei"
    ],
  },
  {
    id: "sigl-stefan",
    name: "Sigl Stefan",
    role: "",
    phone: "08761 684-55",
    email: "stefan.sigl@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer G1.1",
    sachgebiet: "SG Kommunaler Hochbau",
    leitung: [],
    aufgaben: [
      "Kommunaler Hochbau"
    ],
  },
  {
    id: "simmert-tanja",
    name: "Simmert Tanja",
    role: "",
    phone: "08761 684-18",
    email: "ewo@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer R0.01",
    sachgebiet: "SG 12 Einwohnermelde- und Passamt",
    leitung: [],
    aufgaben: [
      "Antragsstatus Reisepass und Personalausweis",
      "Auskunftssperren",
      "Führungszeugnis",
      "Kinderreisepass",
      "Meldeauskünfte",
      "Personalausweis / vorläufiger Personalausweis",
      "Reisepass / vorläufiger Reisepass",
      "Wohnungswechsel - Abmeldung bei der Meldebehörde",
      "Wohnungswechsel - Anmeldung bei der Meldebehörde"
    ],
  },
  {
    id: "sixt-theresa",
    name: "Sixt Theresa",
    role: "",
    phone: "08761 684-820",
    email: "Theresa.Sixt@moosburg.de",
    zimmer: "Huber-Haus, 1. OG, Zimmer H1.1",
    sachgebiet: "SG 13 Personal, Stadtbücherei, Archiv",
    leitung: [],
    aufgaben: [
      "Personalangelegenheiten"
    ],
  },
  {
    id: "sprenger-christoph",
    name: "Sprenger Christoph",
    role: "",
    phone: "08761 684-50",
    email: "christoph.sprenger@moosburg.de",
    zimmer: "Rathaus, EG, Zimmer G1.1",
    sachgebiet: "SG Kommunaler Hochbau",
    leitung: [
      "SG Kommunaler Hochbau"
    ],
    aufgaben: [
      "Kommunaler Hochbau"
    ],
  },
  {
    id: "stadler-evelyn",
    name: "Stadler Evelyn",
    role: "",
    phone: "08761 684-14",
    email: "evelyn.stadler@moosburg.de",
    zimmer: "Huber-Haus, 3. OG, Zimmer H3.1",
    sachgebiet: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: [
      "Geschäftsleitung",
      "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste"
    ],
    aufgaben: [
      "Bürgerbegehren und Bürgerentscheide",
      "Bürgermeister- und Gemeinderatsangelegenheiten",
      "Bürgerversammlungen",
      "Kommunalrecht, allgemeine Angelegenheiten",
      "Ortsrecht",
      "Schüleraustausch",
      "Sitzungsniederschriften",
      "Sitzungsvorbereitung"
    ],
  },
  {
    id: "stanglmayr-christian",
    name: "Stanglmayr Christian",
    role: "",
    phone: "08761 63526",
    email: "Christian.Stanglmayr@moosburg.de",
    zimmer: "",
    sachgebiet: "Wertstoffhof",
    leitung: [],
    aufgaben: [
      "Wertstoffhof"
    ],
  },
  {
    id: "walther-hans",
    name: "Walther Hans",
    role: "",
    phone: "08761 684-813",
    email: "hans.walther@moosburg.de",
    zimmer: "VHS Gebäude",
    sachgebiet: "",
    leitung: [
      "Controlling"
    ],
    aufgaben: [
      "Controlling"
    ],
  },
  {
    id: "wiesheu-sabine",
    name: "Wiesheu Sabine",
    role: "",
    phone: "08761 684-44",
    email: "sabine.wiesheu@moosburg.de",
    zimmer: "Feyerabendhaus, Erdgeschoss",
    sachgebiet: "SG 21 Straßenverkehrsbehörde",
    leitung: [
      "SG 21 Straßenverkehrsbehörde"
    ],
    aufgaben: [
      "Straßenverkehr, Ausnahmegenehmigungen für Veranstaltungen (örtliche Straßenverkehrsbehörde)",
      "Straßenverkehrsordnung; Ausnahmegenehmigungen",
      "Straßenverkehrsordnung; Baustellen",
      "Straßenverkehrsrecht"
    ],
  },
  {
    id: "wimmer-christoph",
    name: "Wimmer Christoph",
    role: "",
    phone: "08761 684-36",
    email: "christoph.wimmer@moosburg.de",
    zimmer: "Feyerabendhaus, 2. Stock, Zimmer 23",
    sachgebiet: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: [],
    aufgaben: [
      "Abmarkung gemeindlicher Grundstücke",
      "Bereitstellung von Bauland",
      "Erbbaurecht",
      "Feldgeschworene",
      "Flurbereinigung",
      "Gewerbeansiedlung",
      "Liegenschaften, An- und Verkauf",
      "Liegenschaften, notarielle Beurkundungen",
      "Liegenschaftsverwaltung (Gemeinde)",
      "Miet- und Pachteinnahmen",
      "Obdachlosigkeit, Vermeidung",
      "Standortberatung",
      "Umlegungsverfahren"
    ],
  },
  {
    id: "winterling-robert",
    name: "Winterling Robert",
    role: "",
    phone: "08761 684-93",
    email: "robert.winterling@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 11",
    sachgebiet: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: [],
    aufgaben: [
      "Informations- und Kommunikationstechnik"
    ],
  },
  {
    id: "zeiler-angelika",
    name: "Zeiler Angelika",
    role: "",
    phone: "08761 684-96",
    email: "angelika.zeiler@moosburg.de",
    zimmer: "Sudetenlandstraße 14",
    sachgebiet: "SG 14 Kraftfahrzeugzulassungsbehörde",
    leitung: [],
    aufgaben: [
      "KFZ-Zulassungswesen"
    ],
  },
  {
    id: "zeiler-manfred",
    name: "Zeiler Manfred",
    role: "",
    phone: "08761 684-91",
    email: "manfred.zeiler@moosburg.de",
    zimmer: "Feyerabendhaus, 1. Stock, Zimmer 11",
    sachgebiet: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: [],
    aufgaben: [
      "Informations- und Kommunikationstechnik"
    ],
  },
  {
    id: "zinitch-herr",
    name: "Zinitch Herr",
    role: "",
    phone: "08761 726020",
    email: "badebetriebe@moosburg.bayern",
    zimmer: "",
    sachgebiet: "Badebetriebe",
    leitung: [],
    aufgaben: [
      "Badebetriebe"
    ],
  },
];

export const sachgebiete: Sachgebiet[] = [
  {
    id: "abteilung-i-allgemeine-verwaltung",
    name: "Abteilung I Allgemeine Verwaltung",
    leitung: "",
    stellvertretung: "Stadler Evelyn",
    weitere: [],
  },
  {
    id: "abteilung-ii-stadtbauamt",
    name: "Abteilung II Stadtbauamt",
    leitung: "Held Herbert",
    stellvertretung: "Graßl Thomas",
    weitere: [],
  },
  {
    id: "abteilung-iii-finanzwesen-versicherungen-steueramt-liegenschaftsamt-stadtkasse",
    name: "Abteilung III Finanzwesen, Versicherungen, Steueramt, Liegenschaftsamt, Stadtkasse",
    leitung: "Krumbucher Martin",
    stellvertretung: "",
    weitere: [],
  },
  {
    id: "badebetriebe",
    name: "Badebetriebe",
    leitung: "",
    stellvertretung: "",
    weitere: [],
  },
  {
    id: "bauhof",
    name: "Bauhof",
    leitung: "",
    stellvertretung: "",
    weitere: [],
  },
  {
    id: "sg-10-geschaeftsleitung-organisation-stadtmarketing-kultur-informations-und-kommunikationstechnik-volksfeste",
    name: "SG 10 Geschäftsleitung, Organisation, Stadtmarketing, Kultur, Informations- und Kommunikationstechnik, Volksfeste",
    leitung: "Stadler Evelyn",
    stellvertretung: "Götz Maximilian",
    weitere: [
      "Burghard Christoph",
      "Jäckel Tim",
      "Pfanzelt Nicole",
      "Winterling Robert",
      "Zeiler Manfred"
    ],
  },
  {
    id: "sg-11-gewerbe-ordnungs-sozial-und-fundamt",
    name: "SG 11 Gewerbe-, Ordnungs-, Sozial-und Fundamt",
    leitung: "",
    stellvertretung: "Kreitmeier Stephanie",
    weitere: [
      "Eitner Fabian",
      "Kaulich Claudia",
      "Littmann Heidemarie"
    ],
  },
  {
    id: "sg-12-einwohnermelde-und-passamt",
    name: "SG 12 Einwohnermelde- und Passamt",
    leitung: "Jüttner Karin",
    stellvertretung: "",
    weitere: [
      "Adamski Madeleine",
      "Kern Angelika",
      "Schmid Verena",
      "Schwaiger Christine",
      "Simmert Tanja"
    ],
  },
  {
    id: "sg-12-standesamt",
    name: "SG 12 Standesamt",
    leitung: "Jüttner Karin",
    stellvertretung: "Holzner Ingrid",
    weitere: [
      "Maier Christine"
    ],
  },
  {
    id: "sg-13-personal-stadtbuecherei-archiv",
    name: "SG 13 Personal, Stadtbücherei, Archiv",
    leitung: "Fischer Johann",
    stellvertretung: "Kaminski Tobias",
    weitere: [
      "Braun Renate",
      "Kopp Stephan",
      "Riedmaier Nicola",
      "Sixt Theresa"
    ],
  },
  {
    id: "sg-14-kraftfahrzeugzulassungsbehoerde",
    name: "SG 14 Kraftfahrzeugzulassungsbehörde",
    leitung: "Schwarzkugler Lisa",
    stellvertretung: "Leicht Gabriele",
    weitere: [
      "Grindl Janine",
      "Schmid Birgit",
      "Zeiler Angelika"
    ],
  },
  {
    id: "sg-20-stadtbau-und-planungsamt-tiefbau-kaufm-leitung-wasserwerk",
    name: "SG 20 Stadtbau- und Planungsamt, Tiefbau, Kaufm. Leitung Wasserwerk",
    leitung: "Held Herbert",
    stellvertretung: "",
    weitere: [
      "Graßl Thomas",
      "Heigl Andreas"
    ],
  },
  {
    id: "sg-21-strassenverkehrsbehoerde",
    name: "SG 21 Straßenverkehrsbehörde",
    leitung: "Wiesheu Sabine",
    stellvertretung: "",
    weitere: [
      "Graßl-Schier Beate",
      "Kollein Florian"
    ],
  },
  {
    id: "sg-22-beitrags-und-gebuehrenstelle",
    name: "SG 22 Beitrags- und Gebührenstelle",
    leitung: "Glück Christina",
    stellvertretung: "",
    weitere: [
      "Schafhauser Michael",
      "Scheckenhofer Marion"
    ],
  },
  {
    id: "sg-30-kaemmerei-steueramt-liegenschaftsamt",
    name: "SG 30 Kämmerei, Steueramt, Liegenschaftsamt",
    leitung: "Krumbucher Martin",
    stellvertretung: "",
    weitere: [
      "Ecke Lea",
      "Gawron Karin",
      "Hadersdorfer Carmen",
      "Hüther Julia",
      "Körger Tanja",
      "Ludwig Anja",
      "Malyssek-Müller Karin",
      "Reif Bettina",
      "Setzensack Ingrid",
      "Wimmer Christoph"
    ],
  },
  {
    id: "sg-31-stadtkasse",
    name: "SG 31 Stadtkasse",
    leitung: "Johal-Mangat Viktoria",
    stellvertretung: "Przybilla Diana",
    weitere: [
      "Kirschner Martina",
      "Reif Bettina",
      "Scherbakow Anna"
    ],
  },
  {
    id: "sg-32-bildungs-und-erziehungswesen-stadtjugendpflege-kvue-parkraumbewirtschaftung",
    name: "SG 32 Bildungs- und Erziehungswesen, Stadtjugendpflege, KVÜ, Parkraumbewirtschaftung",
    leitung: "Morgenstern Aicke",
    stellvertretung: "",
    weitere: [
      "Eichner Laura",
      "Federolf Claudia",
      "Linhart Franz"
    ],
  },
  {
    id: "sg-kommunaler-hochbau",
    name: "SG Kommunaler Hochbau",
    leitung: "Sprenger Christoph",
    stellvertretung: "",
    weitere: [
      "Ebner Michaela",
      "Falkenstein Melanie",
      "Linhart Jacqueline",
      "Schmidt Andreas",
      "Schröder Claudia",
      "Sigl Stefan"
    ],
  },
  {
    id: "stadtgaertnerei",
    name: "Stadtgärtnerei",
    leitung: "",
    stellvertretung: "",
    weitere: [],
  },
  {
    id: "wertstoffhof",
    name: "Wertstoffhof",
    leitung: "",
    stellvertretung: "",
    weitere: [],
  },
];

/** Map of Aufgabe / Dienstleistung -> Ansprechpartner-IDs. */
export const aufgabenToAnsprechpartner: Record<string, string[]> = {
  "Abfallwirtschaft in Gemeinden": ["ecke-lea", "huether-julia", "koerger-tanja"],
  "Abmarkung gemeindlicher Grundstücke": ["wimmer-christoph"],
  "Abwassergebühren": ["glueck-christina", "schafhauser-michael", "scheckenhofer-marion"],
  "Anlagenbuchhaltung": ["ludwig-anja", "malyssek-mueller-karin"],
  "Anmeldung der Eheschließung": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Antragsstatus Reisepass und Personalausweis": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Anzeige einer Geburt": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Aufstellen von Spielgeräten mit Gewinnmöglichkeit - Erlaubnis": ["kreitmeier-stephanie", "littmann-heidemarie"],
  "Auskunftssperren": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Ausstellung von Personenstandsurkunden": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Auszug aus dem Gewerbezentralregister": ["juettner-karin"],
  "Bauberatung": ["held-herbert"],
  "Bauleitplanung": ["grassl-thomas", "held-herbert"],
  "Bauordnungsrecht": ["grassl-thomas"],
  "Baurecht - Erlass örtlicher Bauvorschriften": ["held-herbert"],
  "Beglaubigungen": ["juettner-karin"],
  "Bereitstellung von Bauland": ["wimmer-christoph"],
  "Bestattungsrecht": ["kaulich-claudia"],
  "Bestattungswesen; Überführungserlaubnis": ["kaulich-claudia"],
  "Betretungs- und Befahrverbot von Grundstücken": ["kreitmeier-stephanie"],
  "Breitbandversorgung": ["heigl-andreas"],
  "Brückenbauwerke": ["heigl-andreas"],
  "Bürgerbegehren und Bürgerentscheide": ["goetz-maximilian", "stadler-evelyn"],
  "Bürgermeister- und Gemeinderatsangelegenheiten": ["goetz-maximilian", "stadler-evelyn"],
  "Bürgerversammlungen": ["goetz-maximilian", "stadler-evelyn"],
  "Controlling": ["walther-hans"],
  "Denkmalpflege": ["held-herbert"],
  "Digitalisierung": ["kopp-stephan"],
  "Ehename": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Eheschließung im In- und Ausland": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Erbbaurecht": ["wimmer-christoph"],
  "Erschließungsbeiträge": ["glueck-christina", "grassl-thomas", "scheckenhofer-marion"],
  "Feldgeschworene": ["wimmer-christoph"],
  "Ferienmaßnahmen": ["federolf-claudia", "linhart-franz", "morgenstern-aicke"],
  "Feuerwehrwesen": ["eitner-fabian"],
  "Feuerwerk, Abbrennerlaubnis": ["kaulich-claudia", "kreitmeier-stephanie"],
  "Fischereischein": ["kreitmeier-stephanie", "littmann-heidemarie"],
  "Flurbereinigung": ["wimmer-christoph"],
  "Fundsachen": ["littmann-heidemarie"],
  "Fäkalienabfuhr": ["schafhauser-michael"],
  "Führungszeugnis": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Gastschulverhältnisse": ["linhart-franz", "morgenstern-aicke"],
  "Gaststättenrechtliche Gestattung": ["kaulich-claudia", "kreitmeier-stephanie", "littmann-heidemarie"],
  "Geburtsbeurkundung": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Gewerbeansiedlung": ["wimmer-christoph"],
  "Gewerbeanzeige": ["kaulich-claudia", "kreitmeier-stephanie", "littmann-heidemarie"],
  "Gewerbesteuer": ["ecke-lea", "huether-julia", "koerger-tanja"],
  "Grundsteuer A+B": ["ecke-lea", "huether-julia"],
  "Hallenbelegung": ["ebner-michaela"],
  "Haushaltsplan der Gemeinde": ["krumbucher-martin"],
  "Heimatpflege": ["fischer-johann"],
  "Herstellungbeiträge": ["glueck-christina", "grassl-thomas", "scheckenhofer-marion"],
  "Hundesteuer": ["ecke-lea", "huether-julia", "koerger-tanja"],
  "Informations- und Kommunikationstechnik": ["burghard-christoph", "jaeckel-tim", "winterling-robert", "zeiler-manfred"],
  "Jagdscheinantrag": ["kreitmeier-stephanie"],
  "Jugendzentrum": ["federolf-claudia", "linhart-franz", "morgenstern-aicke"],
  "KFZ-Zulassungswesen": ["brandlmeier-susanne", "grindl-janine", "leicht-gabriele", "schmid-birgit", "schwarzkugler-lisa", "zeiler-angelika"],
  "Katastrophenschutz": ["eitner-fabian"],
  "Kindergarten; Benutzungsordnung": ["morgenstern-aicke"],
  "Kindergartenbeiträge": ["eichner-laura", "federolf-claudia", "linhart-franz", "morgenstern-aicke"],
  "Kinderreisepass": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Kirchenaustritte": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Kleineinleiterabgabe": ["schafhauser-michael"],
  "Klimaschutzmanagerin": ["falkenstein-melanie"],
  "Kommunaler Hochbau": ["ebner-michaela", "linhart-jacqueline", "schmidt-andreas", "schroeder-claudia", "sigl-stefan", "sprenger-christoph"],
  "Kommunalrecht, allgemeine Angelegenheiten": ["goetz-maximilian", "stadler-evelyn"],
  "Konzessionsabgabe": ["krumbucher-martin"],
  "Kostenfreiheit des Schulwegs": ["morgenstern-aicke"],
  "Kämmerei": ["ecke-lea", "huether-julia", "koerger-tanja", "ludwig-anja", "reif-bettina", "setzensack-ingrid"],
  "Ladenschluss": ["kreitmeier-stephanie"],
  "Leichenpass": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Liegenschaften, An- und Verkauf": ["wimmer-christoph"],
  "Liegenschaften, notarielle Beurkundungen": ["wimmer-christoph"],
  "Liegenschaftsverwaltung (Gemeinde)": ["gawron-karin", "hadersdorfer-carmen", "wimmer-christoph"],
  "Marktgebühren": ["kreitmeier-stephanie"],
  "Marktordnung": ["kaulich-claudia", "kreitmeier-stephanie"],
  "Meldeauskünfte": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Miet- und Pachteinnahmen": ["gawron-karin", "hadersdorfer-carmen", "wimmer-christoph"],
  "Mittagsbetreuung an kommunalen Schulen": ["morgenstern-aicke"],
  "Obdachlosigkeit, Vermeidung": ["kreitmeier-stephanie", "wimmer-christoph"],
  "Ordnungswidrigkeiten; Bearbeitung": ["kreitmeier-stephanie"],
  "Ortsrecht": ["goetz-maximilian", "stadler-evelyn"],
  "Parkgebühren, Verordnung über": ["federolf-claudia", "linhart-franz", "morgenstern-aicke"],
  "Personalangelegenheiten": ["fischer-johann", "kaminski-tobias", "riedmaier-nicola", "sixt-theresa"],
  "Personalausweis / vorläufiger Personalausweis": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Plakate, Öffentliche Anschläge": ["kreitmeier-stephanie", "littmann-heidemarie"],
  "Presse- und Öffentlichkeitsarbeit": ["pfanzelt-nicole"],
  "Reisepass / vorläufiger Reisepass": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Rentenanträge; Aufnahme": ["kreitmeier-stephanie"],
  "Rundfunk- und Fernsehgebührenpflicht; Befreiung": ["kreitmeier-stephanie", "littmann-heidemarie"],
  "Schulaufwandsträger": ["morgenstern-aicke"],
  "Schulbuslinien": ["morgenstern-aicke"],
  "Schutz von Sonn- und Feiertagen": ["kaulich-claudia", "kreitmeier-stephanie"],
  "Schüleraustausch": ["goetz-maximilian", "stadler-evelyn"],
  "Sitzungsniederschriften": ["goetz-maximilian", "stadler-evelyn"],
  "Sitzungsvorbereitung": ["goetz-maximilian", "stadler-evelyn"],
  "Sondernutzung an Gemeindestraßen": ["littmann-heidemarie"],
  "Soziale Hilfsstelle": ["kreitmeier-stephanie", "littmann-heidemarie"],
  "Sperrzeit, Gaststätten": ["kreitmeier-stephanie"],
  "Stadtarchiv": ["fischer-johann", "kopp-stephan"],
  "Stadtentwicklung": ["held-herbert"],
  "Stadtkasse": ["johal-mangat-viktoria", "przybilla-diana", "scherbakow-anna"],
  "Stadtplanung": ["held-herbert"],
  "Standortberatung": ["wimmer-christoph"],
  "Stellenangebote": ["braun-renate", "fischer-johann"],
  "Sterbebeurkundung": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Straßenausbaubeiträge": ["glueck-christina", "grassl-thomas", "scheckenhofer-marion"],
  "Straßenbau": ["heigl-andreas"],
  "Straßenreinigung": ["heigl-andreas"],
  "Straßenunterhalt": ["heigl-andreas"],
  "Straßenverkehr, Ausnahmegenehmigungen für Veranstaltungen (örtliche Straßenverkehrsbehörde)": ["grassl-schier-beate", "kollein-florian", "wiesheu-sabine"],
  "Straßenverkehrsordnung; Ausnahmegenehmigungen": ["grassl-schier-beate", "kollein-florian", "wiesheu-sabine"],
  "Straßenverkehrsordnung; Baustellen": ["grassl-schier-beate", "kollein-florian", "wiesheu-sabine"],
  "Straßenverkehrsrecht": ["grassl-schier-beate", "kollein-florian", "wiesheu-sabine"],
  "Städtebauförderung": ["grassl-thomas"],
  "Städtebauliche- und Erschließungsverträge": ["grassl-thomas"],
  "Todesbescheinigungen": ["holzner-ingrid", "juettner-karin", "maier-christine"],
  "Umlegungsverfahren": ["wimmer-christoph"],
  "Umwelt-, Natur- und Landschaftsschutz": ["grassl-thomas"],
  "Unterstützung hilfsbedürftiger Wohnungssuchender": ["kreitmeier-stephanie"],
  "Vereinsförderung": ["ludwig-anja"],
  "Vereinswesen": ["schmid-manuela"],
  "Vergnügungen, öffentliche - Anzeige/Erlaubnis": ["kreitmeier-stephanie", "littmann-heidemarie"],
  "Verkehrsüberwachungsdienst": ["federolf-claudia", "linhart-franz", "morgenstern-aicke"],
  "Vermögenserfassung": ["ludwig-anja", "malyssek-mueller-karin"],
  "Verordnung über Hunde mit gesteigerter Aggressivität und Gefährlichkeit": ["kreitmeier-stephanie"],
  "Verordnung über Hundehaltung in Bayern - Maulkorbzwang und Anleinpflicht": ["kreitmeier-stephanie"],
  "Versicherungswesen": ["malyssek-mueller-karin"],
  "Vorzimmer Bürgermeister/in": ["mermer-petra", "schmid-manuela"],
  "Wassergebühren": ["glueck-christina", "grassl-thomas", "schafhauser-michael", "scheckenhofer-marion"],
  "Wehr- und Zivildienst": ["kreitmeier-stephanie"],
  "Wehrerfassung": ["kreitmeier-stephanie"],
  "Wohngeldantrag": ["juettner-karin"],
  "Wohnsitz - Hauptwohnung und Nebenwohnung": ["juettner-karin"],
  "Wohnungswechsel - Abmeldung bei der Meldebehörde": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Wohnungswechsel - Anmeldung bei der Meldebehörde": ["adamski-madeleine", "juettner-karin", "kern-angelika", "schmid-verena", "schwaiger-christine", "simmert-tanja"],
  "Zahlungsverkehr (Mahnung und Vollstreckung)": ["krumbucher-martin"],
  "Zuweisungen nach dem Finanzausgleichsgesetz": ["krumbucher-martin"],
  "örtliche Rechnungsprüfung": ["krumbucher-martin"],
};

/** Lookup helper: case-insensitive id resolution. */
export function findAnsprechpartner(id: string): Ansprechpartner | undefined {
  const lc = id.toLowerCase();
  return ansprechpartner.find((a) => a.id.toLowerCase() === lc);
}
